server:
  port: 8100


eureka:
  client:
    serviceUrl:
      defaultZone: http://47.107.111.6:8761/eureka
    enabled: true


spring:
  application:
    name: file-manage
  datasource:
    url: jdbc:mysql://47.107.111.6:3306/experiment_platform
    username: root
    password: mysqlmima

