server:
  port: 8100


eureka:
  client:
    serviceUrl:
      defaultZone: http://47.107.111.6:8761/eureka
    enabled: true


spring:
  application:
    name: file-manage
  datasource:
    url: jdbc:mysql://47.107.111.6:3306/experiment_platform
    username: root
    password: mysqlmima
  http:
    encoding:
      charset: UTF-8
  main:
    allow-bean-definition-overriding: true
ribbon:
    ConnectTimeout: 6000
    ReadTimeout: 6000
logging:
  level:
    root: info
  file:
    path: E:/manageData
    name: ${logging.file.path}/%d{yyyy-MM-dd}.log

